openapi: 3.0.0
info:
  title: Product Media API
  description: API для управления медиафайлами товаров (изображения и видео)
  version: 1.0.0

paths:
  /admin/products/{id}/media:
    get:
      summary: Получить все медиафайлы товара
      description: Возвращает список всех медиафайлов (изображений и видео) для указанного товара
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID товара
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
          description: Количество записей на страницу
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: Смещение для пагинации
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  media:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductMedia'
                  count:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer

    post:
      summary: Загрузить медиафайлы для товара
      description: Загружает новые медиафайлы (изображения или видео) для указанного товара
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID товара
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Массив файлов для загрузки (max 10MB каждый)
      responses:
        '201':
          description: Файлы успешно загружены
          content:
            application/json:
              schema:
                type: object
                properties:
                  media:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductMedia'
        '400':
          description: Ошибка валидации (неподдерживаемый тип файла или превышен размер)

  /admin/media/{id}:
    delete:
      summary: Удалить медиафайл
      description: Удаляет указанный медиафайл
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID медиафайла
      responses:
        '200':
          description: Медиафайл успешно удален
          content:
            application/json:
              schema:
                type: object
                properties:
                  deleted:
                    type: boolean
                  id:
                    type: string
        '404':
          description: Медиафайл не найден

  /store/products/{id}/media:
    get:
      summary: Получить медиафайлы товара (Store API)
      description: Возвращает все медиафайлы товара для отображения в магазине
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID товара
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
          description: Количество записей
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: Смещение
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  media:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductMedia'
                  images:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductMedia'
                    description: Только изображения
                  videos:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductMedia'
                    description: Только видео
                  count:
                    type: integer

components:
  schemas:
    ProductMedia:
      type: object
      properties:
        id:
          type: string
          description: Уникальный ID медиафайла
        type:
          type: string
          enum: [image, video]
          description: Тип медиафайла
        url:
          type: string
          description: URL для доступа к файлу
        product_id:
          type: string
          description: ID товара, к которому относится медиафайл
        title:
          type: string
          nullable: true
          description: Название медиафайла
        metadata:
          type: object
          nullable: true
          description: Дополнительные метаданные (file_id, mime_type, size)
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: [] 