name: Test Docker Build

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: medusa-app:test
          
      - name: Test Docker image
        run: |
          docker run --name medusa-test -d medusa-app:test
          sleep 10
          if ! docker ps | grep -q medusa-test; then
            echo "Container failed to start"
            docker logs medusa-test
            exit 1
          fi
          echo "Container started successfully"
          docker logs medusa-test 